port:  5000
markdown: kramdown
name: 上海・开放数据观察
url: city.opendatachina.com/shanghai
title: 上海・开放数据观察
description: 上海・开放数据观察
encoding: utf-8
timezone: China/Beijing
permalink: /:categories/:title
navigation:
- text: 2014-2015数据释放计划
  url: index.html
- text: 发展历程
  url: timeline.html
- text: 资源下载
  url: data.html
- text: 关于
  url: about.html

